USERNAME_MAX_LENGTH = 150
FIRSTNAME_MAX_LENGTH = 150
LASTNAME_MAX_LENGTH = 150
NAME_MAX_LENGTH = 256
INGREDIENT_NAME_MAX_LENGTH = 128
MEASUREMENT_MAX_LENGTH = 64
TAG_MAX_LENGTH = 32
EMAIL_MAX_LENGTH = 254
CONFIRMATION_CODE_MAX_LENGTH = 150


NOT_ALLOWED_USERNAME = "me"
