# Generated by Django 3.2.3 on 2024-09-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="short_link",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                unique=True,
                verbose_name="Короткая ссылка",
            ),
        ),
    ]
