# Generated by Django 3.2.3 on 2024-09-24 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_short_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="short_link",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Короткая ссылка",
            ),
        ),
    ]
